PP584: Add the use of openzeppelin/safeTransfer in the Collector
rsksmart/rif-relay-contracts pull request #100
Opened 2022-11-22 22:38 UTC by AndresQuijano

## What

- Change the use of transfer from ERC20 to safeTransfer from Openzeppelin/SafeERC20

## Why

- Security bug found in REL-005

## Refs

- [PP-584](https://rsklabs.atlassian.net/browse/PP-584)

2022-11-24 09:10 UTC, antomor requested changes
@AndresQuijano the changes look good to me and we should add also some successful scenarios in the tests, to check that the transaction doesn't fail if the transfer is successful.

Furthermore, for the sake of curiosity, have we analyzed the gas consumption change of this addition? I'm wondering if not using the openzeppelin contracts but doing the checks directly would be cheaper.

2022-11-24 22:21 UTC, AndresQuijano commented
> @AndresQuijano the changes look good to me and we should add also some successful scenarios in the tests, to check that the transaction doesn't fail if the transfer is successful.
> 
> Furthermore, for the sake of curiosity, have we analyzed the gas consumption change of this addition? I'm wondering if not using the openzeppelin contracts but doing the checks directly would be cheaper.

As we talked before, I think the success cases are covered by previous test.
Addiotionally this is the report of gas consumption using the different alternatives.
![image](https://user-images.githubusercontent.com/66392159/203869858-5a27ddad-0c23-4e5e-871c-18beb17520f4.png)

2022-11-25 09:34 UTC, ulasanil approved these changes
LGTM

2022-11-28 12:08 UTC, jurajpiar approved these changes
Just a minor improvement.

2022-11-28 15:33 UTC, AndresQuijano commented on test/collector.test.ts
> +            ).to.be.reverted;
I agree. Done.

2022-11-29 09:54 UTC, antomor approved these changes
LGTM

2022-11-29 09:54 UTC, merged