replaced relayWorker with feesReceiver, no collector field
rsksmart/rif-relay-contracts pull request #51
Opened 2022-08-17 20:13 UTC by ironFe93

## What

- collector field removed from transaction detail
- relayWorker field in relayRequest replaced with feesReceiver field
- removed checks for relay worker address in deploy and relay methods
- modified contracts to make possible the removal of the collector field and the inclusion of feesReceiver field

## Why

- This integrates the revenue sharing strategy without having to specify an additional field. Instead, the feesReceiver field can contain an address that will receive fees (either the collector contract or the relay worker)

## Refs

- PP-94, PP-127

2022-08-24 11:55 UTC, antomor requested changes
@ironFe93 Thank you for the changes. I haven't tried yet the whole solution, but I've noticed few things we may need to change

2022-08-24 13:58 UTC, ironFe93 commented on contracts/smartwallet/SmartWallet.sol
> +        address feesReceiver,
must be a leftover from tests. Will remove

2022-08-24 23:27 UTC, ironFe93 commented on contracts/smartwallet/CustomSmartWallet.sol
> +                keccak256("RelayRequest(address relayHub,address from,address to,address tokenContract,uint256 value,uint256 gas,uint256 nonce,uint256 tokenAmount,uint256 tokenGas,bytes data,RelayDat
True, forgot about the custom contracts

2022-08-24 23:29 UTC, ironFe93 commented on contracts/smartwallet/SmartWallet.sol
> +        address feesReceiver,
actually not a leftover, it IS needed because we need to know who will receive the fees, and the feesReceiver field is not present in the req object.

2022-08-24 23:32 UTC, ironFe93 commented on contracts/utils/Eip712Library.sol
> +                hashRelayData(relayRequest.relayData), relayRequest.request, relayRequest.relayData.feesReceiver, signature
This is needed to provide the function in the previous comment with the feesReceiver, unless there is some other way around this, but currently the feesReceiver is not present in relayRequest.request. It IS present in relayRequest.relayData.

2022-08-24 23:34 UTC, ironFe93 commented on contracts/interfaces/IForwarder.sol
> +        address feesReceiver,
feesReceiver is not included in the forwardRequest object

2022-08-24 23:34 UTC, ironFe93 commented on contracts/interfaces/IForwarder.sol
> +        address feesReceiver,
This is the current situation:

`interface EnvelopingTypes {
    struct RelayData {
        uint256 gasPrice;
        address feesReceiver;
        address callForwarder; 
        address callVerifier;
    }

    struct RelayRequest {
        IForwarder.ForwardRequest request;
        RelayData relayData;
    }

    struct DeployRequest {
        IForwarder.DeployRequest request;
        RelayData relayData;
    }
}`

2022-08-26 10:29 UTC, antomor commented on contracts/interfaces/IForwarder.sol
> +        address feesReceiver,
Thank you for the explanation

2022-09-12 21:01 UTC, antomor approved these changes
LGTM

2022-09-12 21:05 UTC, ironFe93 reviewed
lgtm

2022-09-13 19:24 UTC, merged